export const images = [
  {
    carousel: '/img/Pontos_Turisticos/rj.png',
    key: 'RioDeJaneiro',
    cards: '/img/Pontos_Turisticos/rj_media.png',
    title: 'Rio de Janeiro',
    subtitle: 'Brasil',
    capa: '/img/Pontos_Turisticos/capaRIO.png',
    descricao:'Cercada pela Mata Atlântica e com vista para o mar, a cidade do Rio de Janeiro já foi tema de muitas canções que exaltaram sua beleza. E a Cidade Maravilhosa continua linda, com seus cenários de cartão-postal, monumentos, excelente gastronomia e uma vida noturna bem animada. Alguns de seus pontos turísticos são tão famosos que viraram símbolos do Brasil lá fora, como o Cristo Redentor, o Pão de Açúcar e a praia de Copacabana.',
    titulo1:'Cristo Redentor',
    texto1: 'Eleita uma das Sete Novas Maravilhas do Mundo, a estátua do Cristo Redentor reina majestosa sobre a cidade. Fica no alto do Morro do Corcovado e pode ser acessado de van, por uma estrada panorâmica; de trem turístico, que também passa pelo meio da mata; ou de helicóptero, observando a linda vista aérea da cidade. A estátua tem 38 metros de altura e foi inaugurada em 1931.',
    imagem1: '/img/Pontos_Turisticos/cardCristo.jpg',
    titulo2: 'Pão de Açúcar',
    texto2:'Embarque no famoso bondinho construído há mais de um século, rodeado de janelões de vidro. São duas paradas: no Morro da Urca, a 220 metros de altitude, e no Pão de Açúcar, a 396 metros. Lá do alto, é inesquecível a vista da Baía de Guanabara, com suas curvas e barcos ancorados nas marinas. O Morro da Urca também costuma ser palco de shows noturnos.',
    imagem2:'/img/Pontos_Turisticos/cardPao.jpg',
    titulo3: 'Estádio do Maracanã',
    texto3:'Totalmente reformado para a Copa de 2014, o estádio conta com visitas guiadas e impressiona até quando está vazio. Não pode faltar no roteiro dos fanáticos por futebol!',
    imagem3: '/img/Pontos_Turisticos/cardMaraca.jpg',
    titulo4:'Porto Maravilha',
    texto4: 'A região portuária do Centro foi totalmente revitalizada e se tornou a nova sensação do Rio. Além do Museu do Amanhã e do AquaRio, ali ficam o Boulevard Olímpico, com aros olímpicos, e o grafite de Eduardo Kobra, maior painel do mundo segundo o “Guinness Book".',
    imagem4: '/img/Pontos_Turisticos/cardPMaravilha.jpg',
    info:'/img/Pontos_Turisticos/InfoRJ.png',
  },
  {
    carousel: '/img/Pontos_Turisticos/pelourinho.png',
    key: 'Salvador',
    cards: '/img/Pontos_Turisticos/salvador.png',
    title: 'Salvador',
    subtitle: 'Brasil',
    capa: '/img/Pontos_Turisticos/farolSalvador.png',
    descricao:'Terra de todos os santos, com muito axé, sol e mar. Essa é Salvador, que ostentou o título de capital do Brasil por mais de 200 anos. Seja nas ruas de pedra do Pelourinho, no alto do Elevador Lacerda ou nas diversas praias da cidade, a capital da Bahia encanta com seu visual histórico. E durante o Carnaval, não existe lugar no país mais animado do que esta cidade. Veja o nosso pacote de viagem e se divirta como nunca!',
    titulo1:'Pelourinho e Elevador Lacerda',
    texto1: 'Com belas construções barrocas dos séculos 17 e 18, o Centro Histórico de Salvador, na Cidade Alta, é Patrimônio da Humanidade pela UNESCO. Suas ladeiras contam com restaurantes, lojas e bares atrás das fachadas de casarões coloridos. As festas noturnas agitam o Pelourinho, especialmente na terça-feira, com a festa da Benção do Pelô. Uma maneira de chegar ao bairro é pegando o Elevador Lacerda, que liga a Cidade Baixa ao Centro Histórico.',
    imagem1: '/img/Pontos_Turisticos/cardpelourinho.jpg',
    titulo2: 'Fortes de Santa Maria e São Diogo',
    texto2:'Localizados na Barra, os fortes de Santa Maria e São Diogo foram revitalizados e hoje abrigam exposições, um café e uma loja de suvenir. Construídos para proteger a cidade, atualmente são museus audiovisuais. O forte Santa Maria homenageia o fotógrafo francês Pierre Verge, e o Forte São Diogo o artista plástico argentino Carybé. O ingresso é único para as duas atrações e as visitas podem ser feitas a pé. A entrada é gratuita às  quartas-feiras.',
    imagem2:'/img/Pontos_Turisticos/cardForteSanta.jpg',
    titulo3: 'Igreja do Bonfim',
    texto3:'Construída em 1754 para abrigar a imagem do Senhor Bom Jesus trazida de Lisboa em 1745, a igreja tem arquitetura neoclássica com fachada rococó. O santuário é um ícone da fé baiana, atraindo muitos devotos, turistas e peregrinos. As famosas fitinhas são confeccionadas desde o início do século 19 e têm a medida do comprimento do braço direito até o peito da imagem do Senhor do Bonfim.',
    imagem3: '/img/Pontos_Turisticos/cardIgreja.jpg',
    titulo4:'Morro de São Paulo',
    texto4: 'O povoado de Morro de São Paulo não permite a circulação de carros – apenas tratores, jardineiras e os veículos das pousadas. Conheça a badalada Segunda Praia, frequentada por gente jovem e bonita. A praia conta com barracas com música.',
    imagem4: '/img/Pontos_Turisticos/cardMorroSP.jpg',
    info:'/img/Pontos_Turisticos/InfoSalvador.png',
  },
  {
    carousel: '/img/Pontos_Turisticos/olinda_certa.png',
    key: 'Olinda',
    cards: '/img/Pontos_Turisticos/Olinda.png',
    title: 'Olinda',
    subtitle: 'Brasil',
    capa: '/img/Pontos_Turisticos/farolSalvador.png',
    descricao:'Terra de todos os santos, com muito axé, sol e mar. Essa é <strong>Salvador</strong>, que ostentou o título de capital do Brasil por mais de 200 anos. Seja nas ruas de pedra do Pelourinho, no alto do Elevador Lacerda ou nas diversas praias da cidade, a capital da Bahia encanta com seu visual histórico. E durante o Carnaval, não existe lugar no país mais animado do que esta cidade. Veja o nosso pacote de viagem e se divirta como nunca!',
    titulo1:'Pelourinho e Elevador Lacerda',
    texto1: 'Com belas construções barrocas dos séculos 17 e 18, o Centro Histórico de Salvador, na Cidade Alta, é Patrimônio da Humanidade pela UNESCO. Suas ladeiras contam com restaurantes, lojas e bares atrás das fachadas de casarões coloridos. As festas noturnas agitam o Pelourinho, especialmente na terça-feira, com a festa da Benção do Pelô. Uma maneira de chegar ao bairro é pegando o Elevador Lacerda, que liga a Cidade Baixa ao Centro Histórico.',
    imagem1: '/img/Pontos_Turisticos/cardpelourinho.jpg',
    titulo2: 'Fortes de Santa Maria e São Diogo',
    texto2:'Localizados na Barra, os fortes de Santa Maria e São Diogo foram revitalizados e hoje abrigam exposições, um café e uma loja de suvenir. Construídos para proteger a cidade, atualmente são museus audiovisuais. O forte Santa Maria homenageia o fotógrafo francês Pierre Verge, e o Forte São Diogo o artista plástico argentino Carybé. O ingresso é único para as duas atrações e as visitas podem ser feitas a pé. A entrada é gratuita às  quartas-feiras.',
    imagem2:'/img/Pontos_Turisticos/cardForteSanta.jpg',
    titulo3: 'Igreja do Bonfim',
    texto3:'Construída em 1754 para abrigar a imagem do Senhor Bom Jesus trazida de Lisboa em 1745, a igreja tem arquitetura neoclássica com fachada rococó. O santuário é um ícone da fé baiana, atraindo muitos devotos, turistas e peregrinos. As famosas fitinhas são confeccionadas desde o início do século 19 e têm a medida do comprimento do braço direito até o peito da imagem do Senhor do Bonfim.',
    imagem3: '/img/Pontos_Turisticos/cardIgreja.jpg',
    titulo4:'Morro de São Paulo',
    texto4: 'O povoado de Morro de São Paulo não permite a circulação de carros – apenas tratores, jardineiras e os veículos das pousadas. Conheça a badalada Segunda Praia, frequentada por gente jovem e bonita. A praia conta com barracas com música.',
    imagem4: '/img/Pontos_Turisticos/cardMorroSP.jpg',
    info:'/img/Pontos_Turisticos/InfoSalvador.png',
    
  },
  {
    carousel: '/img/Pontos_Turisticos/amsterdam_certa.png',
    key: 'Amsterdam',
    cards: '/img/Pontos_Turisticos/Amsterdam.png',
    title: 'Amsterdam',
    subtitle: 'Holanda',
    capa: '/img/Pontos_Turisticos/capaAmsterdam.png',
    descricao:'Cidade cheia de histórias e opções culturais, Amsterdã é um destino para você se divertir em pubs, bares e festas, além de visitar museus e se deslumbrar pelos canais charmosos que cortam a capital da Holanda. Conheça pontos turísticos famosos, como a Casa de Anne Frank e o Museu Van Gogh. Não deixe de passear de bicicleta, meio de transporte mais utilizado na região, de barco ou mesmo caminhar para ver a arquitetura com estilo medieval. Visite também o Parque das Tulipas, lugar naturalmente colorido por essas flores. Um lugar ótimo também para fazer compras e experimentar pratos deliciosos nos restaurantes.',
    titulo1:'Casa de Anne Frank',
    texto1: 'Confira de perto a casa em que a Anne Frank viveu, hoje um dos museus mais visitados de Amsterdã. A adolescente ficou conhecida depois da publicação de seu diário, repleto de histórias sobre a luta contra a perseguição nazista, durante a segunda guerra mundial. Por lá você conhecerá a famosa estante de livros que dava acesso ao seu esconderijo, um cômodo secreto em que ela e sua família se refugiaram.',
    imagem1: '/img/Pontos_Turisticos/cardAnne.jpg',
    titulo2: 'Praça Nieuwmarkt',
    texto2:'A capital da Holanda é cheia de construções medievais. O lugar que tem tudo isso e muito mais é a praça Nieuwmarkt, tombada como patrimônio da humanidade pela UNESCO. Por lá você vai ver bastante edificações bem conservadas, como a De Waag, antiga edificação do século XV que já serviu como portão de Amsterdã. Ao redor vale muito conferir também pontes e canais, erguidos no século XVI.',
    imagem2:'/img/Pontos_Turisticos/cardNieuwmarkt.jpg',
    titulo3: 'Museu Van Gogh',
    texto3:'Um dos pontos turísticos mais famosos da Holanda, o Museu Van Gogh possui um acervo bastante rico de obras do famoso pintor. O melhor de tudo é que o espaço disponibiliza áudio em português com explicações sobre suas pinturas, além de conhecer mais sobre a vida do artista holandês. No final do passeio não deixe de visitar as lojas de souvenirs e a biblioteca especializada em publicações de arte.',
    imagem3: '/img/Pontos_Turisticos/cardVan.jpg',
    titulo4:'Ponte Magere Brug',
    texto4: 'Na sua viagem para Amsterdã confira a ponte Magere Brug, que fica muito bonita por conta da iluminação noturna. Para chegar lá pode ser a pé ou mesmo de barco. Depois de conhecê-la, uma dica é ir nos restaurantes para experimentar comidas típicas ou mesmo ir em museus.',
    imagem4: '/img/Pontos_Turisticos/cardMagere.jpg',
    info:'/img/Pontos_Turisticos/InfoAmsterdan.png',
  },
  {
    carousel: '/img/Pontos_Turisticos/paris_certa.png',
    key: 'Paris',
    cards: '/img/Pontos_Turisticos/Paris.png',
    title: 'Paris',
    subtitle: 'França',
    capa: '/img/Pontos_Turisticos/capaParis.png',
    descricao:'Um dos destinos mais românticos do mundo, Paris atrai muitos turistas por conta de seus museus, gastronomia ímpar, monumentos importantes e por todas as histórias que cercam a capital da França. Entre os cartões-postais mais importantes que você verá estão a Torre Eiffel, o Museu do Louvre, o Arco do Triunfo e a Catedral de Notre-Dame. Aproveite também para ver espetáculos na Ópera Garnier e shows de cabarés no Moulin Rouge, além de experimentar pratos deliciosos em restaurantes consagrados.',
    titulo1:'Torre Eiffel',
    texto1: 'Maior símbolo de Paris, a Torre Eiffel é um monumento histórico que possui mais de 320 metros de altura e recebe mais de 6 milhões de pessoas ao ano. A obra foi construída em 1889 e projetada pelo engenheiro Gustave Eiffel, daí o nome da construção. Lá você terá 3 andares diferentes para apreciar a vista da capital da França. Aproveite também e jante no conceituado restaurante Jules Verne, localizado no segundo andar.',
    imagem1: '/img/Pontos_Turisticos/cardEiffel.jpg',
    titulo2: 'Palácio de Versalhes',
    texto2:'Visitar o Palácio de Versalhes é uma das paradas obrigatórias para quem vai viajar para Paris, com uma imponente arquitetura e jardins encantadores. Lá destacam-se os aposentos reais e a Galeria dos Espelhos.',
    imagem2:'/img/Pontos_Turisticos/cardVersalhes.jpg',
    titulo3: 'Arco do Triunfo',
    texto3:'Um dos monumentos mais imponentes de Paris, o Arco do Triunfo conta com 50 metros de altura e 45 metros de largura. Localizado na famosa avenida Champs-Élisées, logo no alto da construção você terá uma das vistas mais bonitas de Paris. Aproveite e tire altas fotos. Não irá se arrepender!',
    imagem3: '/img/Pontos_Turisticos/cardArcoTriunfo.jpg',
    titulo4:'Catedral de Notre-Dame',
    texto4: 'A Catedral de Notre-Dame é uma parada obrigatória em Paris e um dos exemplares mais imponentes da arquitetura gótica. A igreja é composta por vitrais, esculturas e gárgulas, além de abrigar fragmentos da coroa de espinhos de Jesus. Ali aconteceram muitos momentos importantes, como a beatificação de Joana D’Arc, ocorrido em 1909.',
    imagem4: '/img/Pontos_Turisticos/cardNotreDame.jpg',
    info:'/img/Pontos_Turisticos/InfoParis.png',
  },
  {
    carousel: '/img/Pontos_Turisticos/porto_certa.png',
    key: 'Porto',
    cards: '/img/Pontos_Turisticos/Porto.png',
    title: 'Porto',
    subtitle: 'Portugal',
    capa: '/img/Pontos_Turisticos/capaRIO.png',
    descricao:'Cercada pela Mata Atlântica e com vista para o mar, a cidade do Rio de Janeiro já foi tema de muitas canções que exaltaram sua beleza. E a Cidade Maravilhosa continua linda, com seus cenários de cartão-postal, monumentos, excelente gastronomia e uma vida noturna bem animada. Alguns de seus pontos turísticos são tão famosos que viraram símbolos do Brasil lá fora, como o Cristo Redentor, o Pão de Açúcar e a praia de Copacabana.',
    titulo1:'Cristo Redentor',
    texto1: 'Eleita uma das Sete Novas Maravilhas do Mundo, a estátua do Cristo Redentor reina majestosa sobre a cidade. Fica no alto do Morro do Corcovado e pode ser acessado de van, por uma estrada panorâmica; de trem turístico, que também passa pelo meio da mata; ou de helicóptero, observando a linda vista aérea da cidade. A estátua tem 38 metros de altura e foi inaugurada em 1931.',
    imagem1: '/img/Pontos_Turisticos/cardCristo.jpg',
    titulo2: 'Pão de Açúcar',
    texto2:'Embarque no famoso bondinho construído há mais de um século, rodeado de janelões de vidro. São duas paradas: no Morro da Urca, a 220 metros de altitude, e no Pão de Açúcar, a 396 metros. Lá do alto, é inesquecível a vista da Baía de Guanabara, com suas curvas e barcos ancorados nas marinas. O Morro da Urca também costuma ser palco de shows noturnos.',
    imagem2:'/img/Pontos_Turisticos/cardPao.jpg',
    titulo3: 'Estádio do Maracanã',
    texto3:'Totalmente reformado para a Copa de 2014, o estádio conta com visitas guiadas e impressiona até quando está vazio. Não pode faltar no roteiro dos fanáticos por futebol!',
    imagem3: '/img/Pontos_Turisticos/cardMaraca.jpg',
    titulo4:'Porto Maravilha',
    texto4: 'A região portuária do Centro foi totalmente revitalizada e se tornou a nova sensação do Rio. Além do Museu do Amanhã e do AquaRio, ali ficam o Boulevard Olímpico, com aros olímpicos, e o grafite de Eduardo Kobra, maior painel do mundo segundo o “Guinness Book".',
    imagem4: '/img/Pontos_Turisticos/cardPMaravilha.jpg',
    info:'/img/Pontos_Turisticos/InfoSalvador.png',
  },
  {
    carousel: '/img/Pontos_Turisticos/ny.png',
    key: 'NovaYork',
    cards: '/img/Pontos_Turisticos/NovaYork.png',
    title: 'Nova York',
    subtitle: 'Estados Unidos',
    capa: '/img/Pontos_Turisticos/capaNY.png',
    descricao:'Seja bem-vindo à Nova York! Uma das cidades mais famosas do mundo, a Big Apple é uma gigante. São 8,5 milhões de habitantes, mais de 400 estações de metrô, milhares de restaurantes, hotéis, teatros, museus e parques. Para todos que procuram por diversão, compras e cultural, esse é o destino ideal! Dividida em cinco regiões: Bronx, Queens, Brooklyn, StatenIsland e Manhattan – a famosa ilha e parte mais rica da cidade - Nova York possui alguns dos pontos turísticos mais conhecidos dos Estados Unidos, como a Estátua da Liberdade, o Central Park e a Times Square. Embarque nessa aventura com a CP& TRAVEL e viva momentos inesquecíveis!',
    titulo1:'Estátua da Liberdade',
    texto1: 'Presente da França aos norte-americanos, o monumento de 93m de altura fica na Ellis Island. Para visitá-la, é preciso pegar uma balsa no Battery Park. A estátua é um símbolo de liberdade e da imigração aos EUA que buscavam uma vida melhor.',
    imagem1: '/img/Pontos_Turisticos/cardLiberdade.jpg',
    titulo2: 'Empire State Building',
    texto2:'Inaugurado em 1929, esse enorme edifício exibe uma bela vista da cidade desde o seu observatório. Por muitos anos foi o edifício mais alto do mundo e ficou famoso por ser cenário do filme “King Kong”.',
    imagem2:'/img/Pontos_Turisticos/cardEmpState.jpg',
    titulo3: 'Central Park',
    texto3:'O parque mais famoso de Nova York está sempre repleto de turistas e nova-iorquinos. No verão, abriga concertos e sessões de cinema ao ar livre. O parque tem playgrounds, prédios históricos e monumentos, como o Strawberry Fields, mosaico em homenagem a John Lennon.',
    imagem3: '/img/Pontos_Turisticos/cardCentralPark.jpg',
    titulo4:'Rockefeller Center',
    texto4: 'O edifício art déco abriga várias lojas, jardins, as estátuas de Prometeu e Atlas, além do mirante Top of The Rock, no alto do prédio. No inverno, as sensações do local são uma pista de patinação no gelo e a famosa árvore de Natal.',
    imagem4: '/img/Pontos_Turisticos/cardRockefeller.jpg',
    info:'/img/Pontos_Turisticos/InfoNY.png',
  },
  {
    carousel: '/img/Pontos_Turisticos/phiphi.png',
    key: 'IPhiPhi',
    cards: '/img/Pontos_Turisticos/Tailandia.png',
    title: 'Ilhas Phi Phi',
    subtitle: 'Tailândia',
    capa: '/img/Pontos_Turisticos/capaRIO.png',
    descricao:'Cercada pela Mata Atlântica e com vista para o mar, a cidade do Rio de Janeiro já foi tema de muitas canções que exaltaram sua beleza. E a Cidade Maravilhosa continua linda, com seus cenários de cartão-postal, monumentos, excelente gastronomia e uma vida noturna bem animada. Alguns de seus pontos turísticos são tão famosos que viraram símbolos do Brasil lá fora, como o Cristo Redentor, o Pão de Açúcar e a praia de Copacabana.',
    titulo1:'Cristo Redentor',
    texto1: 'Eleita uma das Sete Novas Maravilhas do Mundo, a estátua do Cristo Redentor reina majestosa sobre a cidade. Fica no alto do Morro do Corcovado e pode ser acessado de van, por uma estrada panorâmica; de trem turístico, que também passa pelo meio da mata; ou de helicóptero, observando a linda vista aérea da cidade. A estátua tem 38 metros de altura e foi inaugurada em 1931.',
    imagem1: '/img/Pontos_Turisticos/cardCristo.jpg',
    titulo2: 'Pão de Açúcar',
    texto2:'Embarque no famoso bondinho construído há mais de um século, rodeado de janelões de vidro. São duas paradas: no Morro da Urca, a 220 metros de altitude, e no Pão de Açúcar, a 396 metros. Lá do alto, é inesquecível a vista da Baía de Guanabara, com suas curvas e barcos ancorados nas marinas. O Morro da Urca também costuma ser palco de shows noturnos.',
    imagem2:'/img/Pontos_Turisticos/cardPao.jpg',
    titulo3: 'Estádio do Maracanã',
    texto3:'Totalmente reformado para a Copa de 2014, o estádio conta com visitas guiadas e impressiona até quando está vazio. Não pode faltar no roteiro dos fanáticos por futebol!',
    imagem3: '/img/Pontos_Turisticos/cardMaraca.jpg',
    titulo4:'Porto Maravilha',
    texto4: 'A região portuária do Centro foi totalmente revitalizada e se tornou a nova sensação do Rio. Além do Museu do Amanhã e do AquaRio, ali ficam o Boulevard Olímpico, com aros olímpicos, e o grafite de Eduardo Kobra, maior painel do mundo segundo o “Guinness Book".',
    imagem4: '/img/Pontos_Turisticos/cardPMaravilha.jpg',
    info:'/img/Pontos_Turisticos/InfoSalvador.png',
  },
  {
    carousel: '/img/Pontos_Turisticos/mlake.png',
    key: 'MLake',
    cards: '/img/Pontos_Turisticos/Banff.png',
    title: 'Moraine Lake',
    subtitle: 'Canadá',
    capa: '/img/Pontos_Turisticos/capaRIO.png',
    descricao:'Cercada pela Mata Atlântica e com vista para o mar, a cidade do Rio de Janeiro já foi tema de muitas canções que exaltaram sua beleza. E a Cidade Maravilhosa continua linda, com seus cenários de cartão-postal, monumentos, excelente gastronomia e uma vida noturna bem animada. Alguns de seus pontos turísticos são tão famosos que viraram símbolos do Brasil lá fora, como o Cristo Redentor, o Pão de Açúcar e a praia de Copacabana.',
    titulo1:'Cristo Redentor',
    texto1: 'Eleita uma das Sete Novas Maravilhas do Mundo, a estátua do Cristo Redentor reina majestosa sobre a cidade. Fica no alto do Morro do Corcovado e pode ser acessado de van, por uma estrada panorâmica; de trem turístico, que também passa pelo meio da mata; ou de helicóptero, observando a linda vista aérea da cidade. A estátua tem 38 metros de altura e foi inaugurada em 1931.',
    imagem1: '/img/Pontos_Turisticos/cardCristo.jpg',
    titulo2: 'Pão de Açúcar',
    texto2:'Embarque no famoso bondinho construído há mais de um século, rodeado de janelões de vidro. São duas paradas: no Morro da Urca, a 220 metros de altitude, e no Pão de Açúcar, a 396 metros. Lá do alto, é inesquecível a vista da Baía de Guanabara, com suas curvas e barcos ancorados nas marinas. O Morro da Urca também costuma ser palco de shows noturnos.',
    imagem2:'/img/Pontos_Turisticos/cardPao.jpg',
    titulo3: 'Estádio do Maracanã',
    texto3:'Totalmente reformado para a Copa de 2014, o estádio conta com visitas guiadas e impressiona até quando está vazio. Não pode faltar no roteiro dos fanáticos por futebol!',
    imagem3: '/img/Pontos_Turisticos/cardMaraca.jpg',
    titulo4:'Porto Maravilha',
    texto4: 'A região portuária do Centro foi totalmente revitalizada e se tornou a nova sensação do Rio. Além do Museu do Amanhã e do AquaRio, ali ficam o Boulevard Olímpico, com aros olímpicos, e o grafite de Eduardo Kobra, maior painel do mundo segundo o “Guinness Book".',
    imagem4: '/img/Pontos_Turisticos/cardPMaravilha.jpg',
    info:'/img/Pontos_Turisticos/InfoSalvador.png',
  },
];
