export const images = [
  {
    carousel: '/img/Pontos_Turisticos/rj.png',
    key: 'RioDeJaneiro',
    cards: '/img/Pontos_Turisticos/rj_media.png',
    title: 'Rio de Janeiro',
    subtitle: 'Brasil',
  },
  {
    carousel: '/img/Pontos_Turisticos/pelourinho.png',
    key: 'Salvador',
    cards: '/img/Pontos_Turisticos/salvador.png',
    title: 'Salvador',
    subtitle: 'Brasil',
  },
  {
    carousel: '/img/Pontos_Turisticos/olinda_certa.png',
    key: 'Olinda',
    cards: '/img/Pontos_Turisticos/Olinda.png',
    title: 'Olinda',
    subtitle: 'Brasil',
  },
  {
    carousel: '/img/Pontos_Turisticos/amsterdam_certa.png',
    key: 'Amsterdam',
    cards: '/img/Pontos_Turisticos/Amsterdam.png',
    title: 'Amsterdam',
    subtitle: 'Holanda',
  },
  {
    carousel: '/img/Pontos_Turisticos/paris_certa.png',
    key: 'Paris',
    cards: '/img/Pontos_Turisticos/Paris.png',
    title: 'Paris',
    subtitle: 'França',
  },
  {
    carousel: '/img/Pontos_Turisticos/porto_certa.png',
    key: 'Porto',
    cards: '/img/Pontos_Turisticos/Porto.png',
    title: 'Porto',
    subtitle: 'Portugal',
  },
  {
    carousel: '/img/Pontos_Turisticos/ny.png',
    key: 'NovaYork',
    cards: '/img/Pontos_Turisticos/NovaYork.png',
    title: 'Nova York',
    subtitle: 'Estados Unidos',
  },
  {
    carousel: '/img/Pontos_Turisticos/phiphi.png',
    key: 'IPhiPhi',
    cards: '/img/Pontos_Turisticos/Tailandia.png',
    title: 'Ilhas Phi Phi',
    subtitle: 'Tailândia',
  },
  {
    carousel: '/img/Pontos_Turisticos/mlake.png',
    key: 'MLake',
    cards: '/img/Pontos_Turisticos/Banff.png',
    title: 'Moraine Lake',
    subtitle: 'Canadá',
  },
];
